In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
onshore = pd.read_csv('onshore.csv', header = 0, sep = ",", encoding = "big5")

In [3]:
onshore.head()

,accountdate,accountnumber,accountid,accountname,identifycode,birthdate,gendercode,beneficiariescountry,beneficiariestype,telephone1,...,agentcode,agentname,institutioncode,institutionname,salescode,salesname,lifeinsurancefundslicense,ownerid,updatedate,DMID
0,2017/8/25,318225,1219493,林ＯＯ,G221******,1977/8/28,F,臺灣,個人(自然人),NaN,...,311710,NaN,700XXXX,郵局代銷,SEC00TEAM1,TＯam1 SE,NaN,NaN,04:43.7,D30F94F0-CF2C-D6D2-E495-91101AC709A9
1,2017/8/17,318201,1219469,黃ＯＯ,Q223******,1994/2/13,F,臺灣,個人(自然人),NaN,...,R001155043,林Ｏ慧,CY603,CY603,A0567,周Ｏ賢,NaN,NaN,40:48.6,6F9A42BF-6FB3-1D1F-BD2D-DA7B35CEADDF
2,2017/8/29,318232,1219500,林ＯＯ,C121******,1992/12/1,M,臺灣,個人(自然人),02XX321748,...,LF00000001,壽Ｏ通路投信,D4110,北區壽險組,LF00000001,壽Ｏ通路投信,NaN,NaN,40:57.2,33089EEE-2013-9BC2-00D2-0A3747155F2F
3,2017/8/16,318187,1219455,羅ＯＯ,N222******,1965/1/15,F,臺灣,個人(自然人),NaN,...,A0715,郭Ｏ展,D4120,台中分公司,A0715,郭Ｏ展,NaN,NaN,57:42.3,7621EA85-189E-9DE3-A7B1-A974B51942DC
4,2017/9/5,318259,1219525,葉ＯＯ,B120******,1970/2/26,M,臺灣,個人(自然人),04XX739803,...,A0288,龔Ｏ銘,D4120,台中分公司,A0288,龔Ｏ銘,NaN,NaN,26:50.5,256C0068-8779-8CB7-5E62-20E565B795E0

In [4]:
loc = []
for i in onshore["address1_line1"] :
    loc.append(i[:3])
onshore["loc"] = loc
onshore.head()

,accountdate,accountnumber,accountid,accountname,identifycode,birthdate,gendercode,beneficiariescountry,beneficiariestype,telephone1,...,agentname,institutioncode,institutionname,salescode,salesname,lifeinsurancefundslicense,ownerid,updatedate,DMID,loc
0,2017/8/25,318225,1219493,林ＯＯ,G221******,1977/8/28,F,臺灣,個人(自然人),NaN,...,NaN,700XXXX,郵局代銷,SEC00TEAM1,TＯam1 SE,NaN,NaN,04:43.7,D30F94F0-CF2C-D6D2-E495-91101AC709A9,新北市
1,2017/8/17,318201,1219469,黃ＯＯ,Q223******,1994/2/13,F,臺灣,個人(自然人),NaN,...,林Ｏ慧,CY603,CY603,A0567,周Ｏ賢,NaN,NaN,40:48.6,6F9A42BF-6FB3-1D1F-BD2D-DA7B35CEADDF,嘉義縣
2,2017/8/29,318232,1219500,林ＯＯ,C121******,1992/12/1,M,臺灣,個人(自然人),02XX321748,...,壽Ｏ通路投信,D4110,北區壽險組,LF00000001,壽Ｏ通路投信,NaN,NaN,40:57.2,33089EEE-2013-9BC2-00D2-0A3747155F2F,基隆市
3,2017/8/16,318187,1219455,羅ＯＯ,N222******,1965/1/15,F,臺灣,個人(自然人),NaN,...,郭Ｏ展,D4120,台中分公司,A0715,郭Ｏ展,NaN,NaN,57:42.3,7621EA85-189E-9DE3-A7B1-A974B51942DC,彰化縣
4,2017/9/5,318259,1219525,葉ＯＯ,B120******,1970/2/26,M,臺灣,個人(自然人),04XX739803,...,龔Ｏ銘,D4120,台中分公司,A0288,龔Ｏ銘,NaN,NaN,26:50.5,256C0068-8779-8CB7-5E62-20E565B795E0,台中市

In [5]:
onshore["loc"].value_counts()

新北市    20
台北市    15
高雄市    13
台中市    10
桃園市     9
彰化縣     7
台南市     5
基隆市     4
新竹縣     4
新竹市     4
苗栗縣     2
雲林縣     2
屏東縣     1
花蓮縣     1
嘉義縣     1
北縣永     1
嘉義市     1
Name: loc, dtype: int64